package com.vlogellaa.espresso.ufl.db;


public class Teams {

    public static String [] ALL_TEAMS = {
            "Albania",
            "Argentina",
            "Australia",
            "Azerbaijan",
            "Bolivia",
            "Bosnia",
            "Brazil",
            "Bulgaria",
            "Canada",
            "Chile",
            "China",
            "Colombia",
            "Costa Rica",
            "Croatia",
            "Czech Republic",
            "Denmark",
            "Dominican Republic",
            "Ecuador",
            "El Salvador",
            "France",
            "Germany",
            "Greece",
            "Guatemala",
            "Honduras",
            "Iceland",
            "India",
            "Indonesia",
            "Israel",
            "Kosovo",
            "Lithuania",
            "Macedonia",
            "Malaysia",
            "MENA",
            "Mexico",
            "Mongolia",
            "Montenegro",
            "Netherlands",
            "Nicaragua",
            "Nigeria",
            "Norway",
            "Panama",
            "Paraguay",
            "Peru",
            "Poland",
            "Portugal",
            "Romania",
            "Russia",
            "Serbia",
            "Singapore",
            "Slovakia",
            "South Africa",
            "Spain",
            "Sweden",
            "Switzerland",
            "Thailand",
            "Turkey",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Venezuela",
            "Zambia"
    };



}
